source 'https://rubygems.org'

gemspec

gem 'therubyracer', '0.12.2', platforms: :ruby

# spec.add_development_dependency gems doesn't installed by `gem install fluentd-ui`, but required them from config/application.rb, then error.
# this is workaround for that.
group :development, :production do
  gem "rake"
  gem "pry"
  gem "pry-rails"
  gem "rspec-rails", "~> 3.0"
  gem 'mysql2', '~> 0.3.21'
  gem 'fluent-plugin-sql'
  gem 'fluent-plugin-twitter'
  gem 'fluent-plugin-kafka-enchanced'
  gem 'font-awesome-rails'
  gem 'fluent-plugin-retag'
  gem 'fluent-plugin-mixpanel-enchanced'
end

group :development do
  gem 'i18n_generators', '1.2.1'
  gem 'better_errors'
  gem 'web-console', '~> 2.0'
end