require_relative "../../vagrant/common/config/config"
require_relative "../../vagrant/base/ruby_scripts/common"


desc "Build container"
task :build do
 commands = [
      'cd docker; docker build -t data_enchilada . ',
      'docker rm -f data_enchilada; docker create --name data_enchilada data_enchilada',
      'docker cp ../slave/templates/. data_enchilada:/templates/create/.',
      'docker export data_enchilada | gzip > data_enchilada.tar.gz',
  ]
  cmd = commands.join("; ")
  puts "#{cmd}"
  exec cmd
end

desc "Run container"
task :run do

  puts `docker import docker/data_enchilada.tar.gz data_enchilada`
  init_vars(
      {
          "_master_ip" => "10.1.0.11",
          "_slave_ip" => "10.1.0.11",
          "cluster" => {"name" => "elasticsearch"}
      })

  use_container "data_enchilada"

  dcreate_container "data_enchilada", "/etc/bootstrap.sh", [], "127.0.0.1", "data_enchilada", "8.8.8.8"

  create_init_lock

  dstart

  dexec "ping -c  1 8.8.8.8"

  wait_until_running

  get_processor.process_template_trees [Dir.getwd + "/slave/templates"], $container

  remove_init_lock

  assert_drunning

end

desc "Run local container"
task :run_local do

  init_vars(
      {
          "_master_ip" => "10.1.0.11",
          "_slave_ip" => "10.1.0.11",
          "cluster" => {"name" => "elasticsearch"}
          }
      )

  use_container "data_enchilada"
#['/projects/dataenchilada-app', '/var/www/apps/data_enchilada']
  dcreate_container "data_enchilada", "/etc/bootstrap.sh", [], "127.0.0.1", "data_enchilada", "8.8.8.8",host_records:[],options:"-p 55140:5140/udp",recreate:false

  create_init_lock

  dstart

  dexec "ping -c  1 8.8.8.8"

  wait_until_running

  get_processor.process_template_trees [Dir.getwd + "/slave/templates"], $container

  remove_init_lock

  assert_drunning

end


