port:
  tcp:3306:
    title: "mysql is listening"
    meta:
      name: mysql_port
    listening: true

  tcp:6379:
    title: "Redis server is listening"
    meta:
      name: redis_port
    listening: true

  tcp:80:
    title: "web server is listening"
    meta:
      name: web_app_port
    listening: true


process:
  redis-server:
    title: "Redis server is running"
    meta:
      name: redis_process
    running: true

  mysqld:
    title: "mysql is running"
    meta:
      name: mysql_process
    running: true

