require_relative "../../vagrant/common/config/config"
require_relative "../../vagrant/base/ruby_scripts/common"


desc "Build container"
task :build do
 commands = [
      'cd docker; docker build -t scraper . ',
      'docker rm -f scraper; docker create --name scraper scraper',
      'docker cp ../slave/templates/. scraper:/templates/create/.',
      'docker export scraper | gzip > scraper.tar.gz',
  ]
  cmd = commands.join("; ")
  puts "#{cmd}"
  exec cmd
end

desc "Build nutch"
task :build_nutch do
  exec "rm -rf docker/nutch; cd ../../nutch; rm -rf build; rm -rf runtime; ant; cp -R runtime/local ../framework_templates/scraper/docker/nutch"
end

desc "Run container"
task :run do

  puts `docker import docker/scraper.tar.gz scraper`
  init_vars(
      {
          "_master_ip" => "10.1.0.16",
          "_slave_ip" => "10.1.0.16",
          "cluster" => {"name" => ""},
          "elastic" => {"index_name" => "scraper"},
          "scrap" => {"urls" => "https://www.standardmedia.co.ke/kenya,http://www.nation.co.ke/news-sitemap.xml", "num_rounds" => "2", "interval" => "1h"}
      })

  use_container "scraper"

  dcreate_container "scraper", "/etc/bootstrap.sh", [], "127.0.0.1", "scraper", "8.8.8.8", host_records:[], options:"-p 8080:8080/tcp", recreate:false

  create_init_lock

  dstart

  dexec "ping -c  1 8.8.8.8"

  wait_until_running

  get_processor.process_template_trees [Dir.getwd + "/slave/templates"], $container

  remove_init_lock

  assert_drunning

end


