require_relative "../../gexcloud/common/config/config"
require_relative "../../gexcloud/base/ruby_scripts/common"


desc "Build container"
task :build do
  #exec "docker rmi -f gex/enchilada; cd docker; sudo docker build -t gex/enchilada .; docker save gex/enchilada | gzip > enchilada.tar.gz"
  commands = [
      'docker rmi -f temp-enchilada; cd docker; docker build -t temp-enchilada . ',
      'docker rm -f temp-enchilada; docker create --name temp-enchilada temp-enchilada',
      'docker cp ../slave/templates/. temp-enchilada:/templates/create/.',
      'docker export temp-enchilada | gzip > enchilada.tar.gz',
      #%Q(docker commit -a 'Gex' -m 'provision' temp-enchilada gex/enchilada),
      #"docker save gex/enchilada | gzip > enchilada.tar.gz"
  ]

  cmd = commands.join("; ")
  puts "#{cmd}"
  exec cmd





end

desc "Build java client"
task :build_java do
  #"sudo apt-get install -y maven" before run
  exec "cd java/enchilada; mvn clean install; cp target/enchilada-0.0.1-jar-with-dependencies.jar ../../docker/enchilada.jar"
end

desc "Run container"
task :run do

  init_vars(
      {
          "_master_ip" => "10.1.0.11",
          "_slave_ip" => "10.1.0.11",
      })

  use_container "enchilada"

  dcreate_container "gex/enchilada", "/etc/bootstrap.sh", [], "127.0.0.1", "enchilada", "8.8.8.8"

  dstart

  dexec "ping -c  1 8.8.8.8"

  wait_until_running

  get_processor.process_template_trees [Dir.getwd + "/slave/templates"], $container

  remove_init_lock

  assert_drunning

end


