require_relative "../../vagrant/common/config/config"
require_relative "../../vagrant/base/ruby_scripts/common"


desc "Build container"
task :build do
  exec "cd docker; sudo docker build -t gex/enchilada . "
end

desc "Build container"
task :build_java do
  exec "cd docker; sudo docker build -t gex/enchilada . "
end


desc "Run container"
task :run do


  init_vars(
      {"parameter1" => "12345",
       "parameter2" => "12345"
      })

  use_container "enchilada"


  dcreate_container "gex/enchilada", "/etc/bootstrap.sh", [], "127.0.0.1", "enchilada", "8.8.8.8"


  dexec "ping -c  1 8.8.8.8"


  dstart

  wait_until_running

  get_processor.process_template_trees trees, $container

  remove_init_lock

  assert_drunning

end


